default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: bbfh
  password: bbfh

development:
  <<: *default
  database: bbfh_dev

test:
  <<: *default
  database: bbfh_test

production:
  <<: *default
  database: bbfh_prod
